services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.8.0
    container_name: mealie
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mealie.rule=Host(`mealie.lab1830.com`)"
      - "traefik.http.routers.mealie.entrypoints=websecure"
      - "traefik.http.routers.mealie.tls.certresolver=letsencrypt"
      - "traefik.http.services.mealie.loadbalancer.server.port=9000"
      - "traefik.http.routers.mealie-insecure.rule=Host(`mealie.lab1830.com`)"
      - "traefik.http.routers.mealie-insecure.entrypoints=web"
      - "traefik.http.routers.mealie-insecure.middlewares=redirect-to-https"
      - com.centurylinklabs.watchtower.enable=true
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - mealie-data:/app/data/
    environment:
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
      BASE_URL: https://mealie.lab1830.com
      DEFAULT_EMAIL: "admin@lab1830.com"
      DEFAULT_PASSWORD: "changeme123"
      DB_ENGINE: sqlite
      AUTO_BACKUP_ENABLED: "true"

volumes:
  mealie-data:

networks:
  web:
    external: true