services:
  pi-proxy:
    image: traefik/whoami # dummy container
    container_name: pi-proxy
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.lab1830.com`)"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.service=pihole-service"
      - "traefik.http.services.pihole-service.loadbalancer.server.url=https://192.168.4.254/admin/login"

networks:
  web:
    external: true