# /home/blehnen/docker/stacks/socket-proxy/compose.yaml
services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: socket-proxy
    restart: unless-stopped
    environment:
      # Docker Socket Proxy Access Control
      CONTAINERS: 1
      IMAGES: 1
      INFO: 1
      PING: 1
      EVENTS: 1
      NETWORKS: 1
      SYSTEM: 1
      VOLUMES: 1
      # Everything else disabled for security
      BUILD: 0
      COMMIT: 0
      CONFIGS: 0
      NODES: 0
      SECRETS: 0
      SERVICES: 0
      SWARM: 0
      TASKS: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    expose:
      - "2375"
    networks:
      - socket_proxy

networks:
  socket_proxy:
    name: socket_proxy
    driver: bridge
