services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: unless-stopped
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/blehnen/docker/appdata/dockge:/app/data
      - /home/blehnen/docker/stacks:/app/stacks
    environment:
      - DOCKGE_STACKS_DIR=/app/stacks
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dockge.rule=Host(`dockge.lab1830.com`)"
      - "traefik.http.routers.dockge.entrypoints=websecure"
      - "traefik.http.routers.dockge.tls=true"
      - "traefik.http.services.dockge.loadbalancer.server.port=5001"
      - "traefik.http.routers.dockge.tls.certresolver=letsencrypt"

networks:
  web:
    external: true