# File: /home/blehnen/docker/stacks/speedtest-tracker/compose.yaml
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:1.6.1
    container_name: speedtest-tracker
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: America/Chicago
      PUID: 1000
      PGID: 1000
      APP_KEY: ${SPEEDTEST_APP_KEY}
      DB_CONNECTION: sqlite
      SPEEDTEST_SCHEDULE: 0 */6 * * *  # Every 6 hours
      SPEEDTEST_SERVERS:           # Auto-select best servers
      PRUNE_RESULTS_OLDER_THAN: 90  # Keep 90 days of results
      DISPLAY_TIMEZONE: America/Chicago
      FORCE_HTTPS: false
    volumes:
      - /home/blehnen/docker/appdata/speedtest-tracker:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.speedtest.rule=Host(`speedtest.lab1830.com`)"
      - "traefik.http.routers.speedtest.entrypoints=websecure"
      - "traefik.http.routers.speedtest.tls=true"
      - "traefik.http.routers.speedtest.tls.certresolver=letsencrypt"
      - "traefik.http.services.speedtest.loadbalancer.server.port=80"
      - com.centurylinklabs.watchtower.enable=true

networks:
  web:
    external: true

# Uncomment for PostgreSQL instead of SQLite
#  db:
#    image: postgres:15
#    container_name: speedtest-db
#    restart: unless-stopped
#    environment:
#      POSTGRES_DB: speedtest_tracker
#      POSTGRES_USER: speedtest
#      POSTGRES_PASSWORD: CHANGE_THIS_PASSWORD
#    volumes:
#      - ./postgres:/var/lib/postgresql/data
#    networks:
#      - proxy