services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/blehnen/docker/appdata/grocy:/config
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - traefik.enable=true
      - traefik.http.routers.grocy.rule=Host(`grocy.lab1830.com`)
      - traefik.http.routers.grocy.entrypoints=websecure
      - traefik.http.routers.grocy.tls=true
      - traefik.http.routers.grocy.tls.certresolver=letsencrypt
      - traefik.http.services.grocy.loadbalancer.server.port=80
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - web

networks:
  web:
    external: true